api_platform:
    title: Google News API
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    formats:
    docs_formats:
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

when@prod:
    api_platform:
        graphql:
            default_ide: false
            introspection: false
        enable_docs: false
        enable_entrypoint: false
        enable_swagger: false
        enable_swagger_ui: false
